name: gecko_breeder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 파이어베이스 및 필수 도구
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.0
  image_picker: ^1.1.0
  fl_chart: ^0.68.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  uuid: ^4.0.0
  table_calendar: ^3.0.9  
  photo_view: ^0.14.0   # 사진 확대/축소 보기 기능
  cached_network_image: ^3.3.0 # 인터넷 사진을 부드럽게 로딩하고 캐싱
  
  # 인쇄 관련 패키지 (중복 제거됨!)
  printing: ^5.13.1
  pdf: ^3.11.3
  
  # 기본 아이콘
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true